### ISSUE TITLE
Awesome! And a suggestion

### ISSUE THREAD

**Issue by amarpMSFT** [alessiot89/D3D12QuickRef#1]
This is fantastic!

A suggestion: For data structures that have D3DX12 helpers, it might be handy to mention the names of the helpers or somehow link to them, perhaps in a subtle way that doesn't distract from the nice purity you have in showing all the raw interfaces.  The intro could point to where to find the D3DX12 header on GitHub (which I don't actually know offhand, but others can point you to if you haven't found it).

**Comment by alessiot89** [comment]
Thank you.
D3DX12 was one of the things I considered to attach but I was afraid to add to much raw code. Your solution looks a lot better.
I will also add other useful links like the MS DX YouTube channel and some interesting MSDN blogs and other github projects. I may create a dedicated section at the end of the document.
