### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by alisonst** [alessiot89/D3D12QuickRef#2]
We wanted more people to see it, so I tweeted it from the @directx12 account: https://twitter.com/DirectX12/status/713063449283010560

**Comment by alessiot89** [comment]
Thank you :+1:

**Comment by alisonst** [comment]
Hi Alessio,
I’d love to chat for a little, if you have a chance. Can you give me your “real” email address? And, I have something to send you… but I need your home or work address.

That reference card is so great. ☺
Alison

**Comment by alessiot89** [comment]
I sent you an email (:
